redis:
    container_name: redis:alpine
    image: redis
    ports:
      - 6379:6379
    restart: always

php:
  image: php:7.2
  container_name: php
  volumes:
    - .:/var/www/html/raspberry
  entrypoint:
    - php-fpm

nginx:
  image: nginx:alpine
  container_name: nginx
  volumes:
    - ./nginx.conf:/etc/nginx/conf.d/default.conf
  links:
    - php
  ports:
    - 80:80